apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-python
  template:
    metadata:
      labels:
        app: hello-python
    spec:
      containers:
      - name: hello-python
        image: python-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: hello-python-service
spec:
  type: NodePort
  selector:
    app: hello-python
  ports:
  - targetPort: 5000
    port: 5000
    nodePort: 30001
